import React from "react";
import {
    LayoutGrid,
    UserCog,
    CircleDollarSign,
    Laptop,
    GitBranch,
    Presentation,
    Video,
    ShieldAlert,
    TrendingUp,
    TrendingDown,
    GraduationCap,
    FileCheck,
    CalendarDays,
    MonitorPlay,
    PencilRuler,
    CalendarRange,
    FileSignature,
    Users2,
    MessagesSquare,
    CloudDownload,
    BookText,
    LibraryBig,
    Box,
    Contact,
    Truck
} from "lucide-react";

export interface SubMenuItem {
    title: string;
    url: string;
}

export interface MenuItem {
    title: string;
    url: string;
    icon: React.ReactNode;
    dropdown: boolean;
    submenu: (SubMenuItem | string)[];
}

export const menu: MenuItem[] = [
    {
        title: "Dashboard",
        url: "/admin/dashboard",
        icon: <LayoutGrid size={20} />,
        dropdown: false,
        submenu: [],
    },
    {
        title: "Students",
        url: "",
        icon: <UserCog size={20} />,
        dropdown: true,
        submenu: [
            { title: "Student Details", url: "/admin/Students/StudentDetails" },
            { title: "Student Admission", url: "/admin/Students/Create" },
            { title: "Online Admission", url: "/admin/Students/onlineAdmission" },
            { title: "Disabled Students", url: "/admin/Students/disableStudentsList" },
            { title: "Bulk Delete", url: "/admin/Students/BulkDelete" },
            { title: "Student Categories", url: "/admin/Students/StudentCategory" },
            { title: "Student House", url: "/admin/Students/schoolhouse" },
            { title: "Disable Reason", url: "/admin/Students/DisableReason" },
        ],
    },
    {
        title: "Fees",
        url: "",
        icon: <CircleDollarSign size={20} />,
        dropdown: true,
        submenu: [
            { title: "Collect Fees", url: "/admin/FeesCollection/studentfee" },
            { title: "Offline Bank Payments", url: "/admin/FeesCollection/offlinepayment" },
            { title: "Search Fees Payment", url: "/admin/FeesCollection/SearchPayment" },
            { title: "Search Due Fees", url: "/admin/FeesCollection/FeeSearch" },
            { title: "Fees Master", url: "/admin/FeesCollection/feemaster" },
            { title: "Quick Fees", url: "/admin/FeesCollection/QuickFees" },
            { title: "Fees Group", url: "/admin/FeesCollection/feegroup" },
            { title: "Fees Type", url: "/admin/FeesCollection/feetype" },
            { title: "Fees Discount", url: "/admin/FeesCollection/feediscount" },
            { title: "Fees Carry Forward", url: "/admin/FeesCollection/feesforward" },
            { title: "Fees Reminder", url: "/admin/FeesCollection/feereminder" },
        ],
    },
    {
        title: "Online Course",
        url: "",
        icon: <Laptop size={20} />,
        dropdown: true,
        submenu: [
            { title: "Online Course", url: "/admin/onlinecourse/course" },
            { title: "Offline Payment", url: "/admin/onlinecourse/offlinepayment" },
            { title: "Course Category", url: "/admin/onlinecourse/coursecategory" },
            { title: "Question Bank", url: "/admin/onlinecourse/courseexamquestion" },
            { title: "Online Course Report", url: "/admin/onlinecourse/OnlineCourseReport" },
            { title: "Setting", url: "/admin/onlinecourse/setting" },
        ],
    },
    {
        title: "Multi Branch",
        url: "",
        icon: <GitBranch size={20} />,
        dropdown: true,
        submenu: [
            { title: "Overview", url: "/admin/multibranch/overview" },
            { title: "Report", url: "/admin/multibranch/report" },
            { title: "Setting", url: "/admin/multibranch/branch" },
        ],
    },
    {
        title: "Gmeet Live Classes",
        url: "",
        icon: <Presentation size={20} />,
        dropdown: true,
        submenu: [
            { title: "Live Classes", url: "/admin/GmeetLiveClasses/liveClasses" },
            { title: "Live Meeting", url: "/admin/GmeetLiveClasses/liveMeeting" },
            { title: "Live Classes Report", url: "/admin/GmeetLiveClasses/LiveClassesReport" },
            { title: "Live Meeting Report", url: "/admin/GmeetLiveClasses/LiveMeetingReport" },
            { title: "Setting", url: "/admin/GmeetLiveClasses/setting" },
        ],
    },
    {
        title: "Zoom Live Class",
        url: "",
        icon: <Video size={20} />,
        dropdown: true,
        submenu: [
            { title: "Live Classes", url: "/admin/ZoomLiveClasses/liveClasses" },
            { title: "Live Meeting", url: "/admin/ZoomLiveClasses/liveMeeting" },
            { title: "Live Classes Report", url: "/admin/ZoomLiveClasses/LiveClassesReport" },
            { title: "Live Meeting Report", url: "/admin/ZoomLiveClasses/LiveMeetingReport" },
            { title: "Setting", url: "/admin/ZoomLiveClasses/setting" },
        ],
    },
    {
        title: "Behaviour",
        url: "",
        icon: <ShieldAlert size={20} />,
        dropdown: true,
        submenu: [
            { title: "Assign Incident", url: "/admin/behaviourRecords/AssignIncident" },
            { title: "Incidents", url: "/admin/behaviourRecords/Incidents" },
            { title: "Reports", url: "/admin/behaviourRecords/Reports" },
            { title: "Setting", url: "/admin/behaviourRecords/Setting" },
        ],
    },
    {
        title: "Income",
        url: "",
        icon: <TrendingUp size={20} />,
        dropdown: true,
        submenu: [
            { title: "Add Income", url: "/admin/income/addIncome" },
            { title: "Search Income", url: "/admin/income/searchIncome" },
            { title: "Income Head", url: "/admin/income/incomeHead" },
        ],
    },
    {
        title: "Expenses",
        url: "",
        icon: <TrendingDown size={20} />,
        dropdown: true,
        submenu: [
            { title: "Add Expense", url: "/admin/expenses/addExpense" },
            { title: "Search Expense", url: "/admin/expenses/searchExpense" },
            { title: "Expense Head", url: "/admin/expenses/expenseHead" },
        ],
    },
    {
        title: "CBSE Examination",
        url: "",
        icon: <GraduationCap size={20} />,
        dropdown: true,
        submenu: [
            { title: "Exam", url: "/admin/cbseexam/Exam" },
            { title: "Exam Schedule", url: "/admin/cbseexam/ExamSchedule" },
            { title: "Print Marksheet", url: "/admin/cbseexam/PrintMarksheet" },
            { title: "Exam Grade", url: "/admin/cbseexam/ExamGrade" },
            { title: "Assign Observation", url: "/admin/cbseexam/AssignObservation" },
            { title: "Observation", url: "/admin/cbseexam/Observation" },
            { title: "Observation Parameter", url: "/admin/cbseexam/ObservationParameter" },
            { title: "Assessment", url: "/admin/cbseexam/Assessment" },
            { title: "Term", url: "/admin/cbseexam/Term" },
            { title: "Template", url: "/admin/cbseexam/Template" },
            { title: "Reports", url: "/admin/cbseexam/Reports" },
            { title: "Setting", url: "/admin/cbseexam/Setting" },
        ],
    },
    {
        title: "Examinations",
        url: "",
        icon: <FileCheck size={20} />,
        dropdown: true,
        submenu: [
            { title: "Exam Group", url: "/admin/Examinations/ExamGroup" },
            { title: "Exam Schedule", url: "/admin/Examinations/ExamSchedule" },
            { title: "Exam Result", url: "/admin/Examinations/ExamResult" },
            { title: "Design AdmitCard", url: "/admin/Examinations/DesignAdmitCard" },
            { title: "Print AdmitCard", url: "/admin/Examinations/PrintAdmitCard" },
            { title: "Design Marksheet", url: "/admin/Examinations/DesignMarksheet" },
            { title: "Print Marksheet", url: "/admin/Examinations/PrintMarksheet" },
            { title: "Marks Grade", url: "/admin/Examinations/MarksGrade" },
            { title: "Marks Division", url: "/admin/Examinations/MarksDivision" },
        ],
    },
    {
        title: "Attendance",
        url: "",
        icon: <CalendarDays size={20} />,
        dropdown: true,
        submenu: [
            { title: "Student Attendance", url: "/admin/Attendance/StudentAttendance" },
            { title: "Attendance By Date", url: "/admin/Attendance/AttendanceByDate" },
            { title: "Approve Leave", url: "/admin/Attendance/ApproveLeave" },
        ],
    },
    {
        title: "Online Examinations",
        url: "",
        icon: <MonitorPlay size={20} />,
        dropdown: true,
        submenu: [
            { title: "Online Exam", url: "/admin/OnlineExaminations/OnlineExam" },
            { title: "Question Bank", url: "/admin/OnlineExaminations/QuestionBank" },
        ],
    },
    {
        title: "Academics",
        url: "",
        icon: <PencilRuler size={20} />,
        dropdown: true,
        submenu: [
            { title: "Class Timetable", url: "/admin/Academics/ClassTimetable" },
            { title: "Teachers Timetable", url: "/admin/Academics/ClassTimetable" },
            { title: "Assign Class Teacher", url: "/admin/Academics/AssignClassTeacher" },
            { title: "Promote Students", url: "/admin/Academics/PromoteStudents" },
            { title: "Subject Group", url: "/admin/Academics/SubjectGroup" },
            { title: "Subjects", url: "/admin/Academics/Subjects" },
            { title: "Class", url: "/admin/Academics/Class" },
            { title: "Sections", url: "/admin/Academics/Sections" },
        ],
    },
    {
        title: "Annual Calendar",
        url: "",
        icon: <CalendarRange size={20} />,
        dropdown: true,
        submenu: [
            { title: "Annual Calendar", url: "/admin/AnnualCalendar" },
            { title: "Holiday Type", url: "/admin/AnnualCalendar/HolidayType" },
        ],
    },
    {
        title: "Lesson Plan",
        url: "",
        icon: <FileSignature size={20} />,
        dropdown: true,
        submenu: [
            { title: "Copy Old Lessons", url: "/admin/LessonPlan/CopyOldLessons" },
            { title: "Manage Lesson Plan", url: "/admin/LessonPlan/ManageLessonPlan" },
            { title: "Manage Syllabus Status", url: "/admin/LessonPlan/ManageSyllabusStatus" },
            { title: "Lesson", url: "/admin/LessonPlan/Lesson" },
            { title: "Topic", url: "/admin/LessonPlan/Topic" },
        ],
    },
    {
        title: "HR",
        url: "",
        icon: <Users2 size={20} />,
        dropdown: true,
        submenu: [
            { title: "Staff Directory", url: "/admin/hr/staffDirectory" },
            { title: "Staff Attendance", url: "/admin/hr/staffAttendance" },
            { title: "Payroll", url: "/admin/hr/payroll" },
            { title: "Approve Leave Request", url: "/admin/hr/approveLeave" },
            { title: "Apply Leave", url: "/admin/hr/applyLeave" },
            { title: "Leave Type", url: "/admin/hr/leaveType" },
            { title: "Teachers Rating", url: "/admin/hr/teachersRating" },
            { title: "Department", url: "/admin/hr/department" },
            { title: "Designation", url: "/admin/hr/designation" },
            { title: "Disabled Staff", url: "/admin/hr/disabledStaff" },
        ],
    },
    {
        title: "Communication",
        url: "",
        icon: <MessagesSquare size={20} />,
        dropdown: true,
        submenu: [
            { title: "Notice Board", url: "/admin/Communicate/NoticeBoard" },
            { title: "Send Email", url: "/admin/Communicate/SendEmail" },
            { title: "Send SMS", url: "/admin/Communicate/SendSMS" },
            { title: "Email / SMS Log", url: "/admin/Communicate/EmailSMSLog" },
            { title: "Schedule Email SMS Log", url: "/admin/Communicate/ScheduleEmailSMSLog" },
            { title: "Login Credentials Send", url: "/admin/Communicate/LoginCredentialsSend" },
            { title: "Email Template", url: "/admin/Communicate/EmailTemplate" },
            { title: "SMS Template", url: "/admin/Communicate/SMSTemplate" },
        ],
    },
    {
        title: "Download Center",
        url: "",
        icon: <CloudDownload size={20} />,
        dropdown: true,
        submenu: [
            { title: "Content Type", url: "/admin/DownloadCenter/ContentType" },
            { title: "Content Share List", url: "/admin/DownloadCenter/ContentShareList" },
            { title: "Upload/Share Content", url: "/admin/DownloadCenter/UploadShareContent" },
            { title: "Video Tutorial", url: "/admin/DownloadCenter/VideoTutorial" },
        ],
    },
    {
        title: "Homework",
        url: "",
        icon: <BookText size={20} />,
        dropdown: true,
        submenu: [
            { title: "Add Homework", url: "/admin/Homework/AddHomework" },
            { title: "Daily Assignment", url: "/admin/Homework/DailyAssignment" },
        ],
    },
    {
        title: "Library",
        url: "",
        icon: <LibraryBig size={20} />,
        dropdown: true,
        submenu: [
            { title: "Book List", url: "/admin/Library/BookList" },
            { title: "Issue - Return", url: "/admin/Library/IssueReturn" },
            { title: "Add Student", url: "/admin/Library/AddStudent" },
            { title: "Add Staff Member", url: "/admin/Library/AddStaffMember" },
        ],
    },
    {
        title: "Inventory",
        url: "",
        icon: <Box size={20} />,
        dropdown: true,
        submenu: [
            { title: "Issue Item", url: "/admin/Inventory/IssueItem" },
            { title: "Add Item Stock", url: "/admin/Inventory/AddItemStock" },
            { title: "Add Item", url: "/admin/Inventory/AddItem" },
            { title: "Item Category", url: "/admin/Inventory/ItemCategory" },
            { title: "Item Store", url: "/admin/Inventory/ItemStore" },
            { title: "Item Supplier", url: "/admin/Inventory/ItemSupplier" },
        ],
    },
    {
        title: "Student CV",
        url: "",
        icon: <Contact size={20} />,
        dropdown: true,
        submenu: [
            { title: "Build CV", url: "/admin/StudentCV/BuildCV" },
            { title: "Download CV", url: "/admin/StudentCV/DownloadCV" },
        ],
    },
    {
        title: "Transport",
        url: "",
        icon: <Truck size={20} />,
        dropdown: true,
        submenu: [
            { title: "Fees Master", url: "/admin/Transport/FeesMaster" },
            { title: "Pickup Point", url: "/admin/Transport/PickupPoint" },
            { title: "Routes", url: "/admin/Transport/Routes" },
            { title: "Vehicles", url: "/admin/Transport/Vehicles" },
            { title: "Assign Vehicle", url: "/admin/Transport/AssignVehicle" },
            { title: "Route Pickup Point", url: "/admin/Transport/RoutePickupPoint" },
            { title: "Student Transport Fees", url: "/admin/Transport/StudentTransportFees" },
        ],
    },
];
